---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: media-app
spec:
  maxReplicas: 10
  metrics:
    -
      resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: media-app
